name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: postmanlabs/postman-action@v1
      with:
        api_key: ${{ secrets.POSTMAN_API_KEY }}
        collection: https://www.postman.com/warped-comet-548845/workspace/rcpt/collection/26687611-b306ba01-4fc6-42fd-947e-1982c00f472d?action=share&creator=26687611
