name: Test Postman Collection

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Newman
      run: npm install -g newman
    - name: Run Postman tests
      run: newman run "https://api.getpostman.com/collections/24371688-803c9bf5-2198-41b4-a300-4dff364a641d?apikey=PMAK-6429b97800c08413f6e7ab26-a4581caa06e181a2f7d64596d9e121de12" --environment "tests/rec_railway_azat.postman_environment.json"
