name: Test Postman Collection

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Newman
      run: npm install -g newman
    - name: Run Postman tests
      run: newman run https://github.com/BayAzat/rcpt/blob/main/Recipetoria.postman_collection.json --environment https://github.com/BayAzat/rcpt/blob/main/rec_railway_azat.postman_environment.json
