name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: postmanlabs/postman-action@v1
      with:
           api_key: ${{ secrets.POSTMAN_API_KEY }}
           collection: https://api.postman.com/collections/24371688-803c9bf5-2198-41b4-a300-4dff364a641d?access_key=PMAT-01GWYXFZX9KGM5BRRDGK3CYVDQ
