name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: postmanlabs/postman-action@v1
      with:
        api_key: ${{ secrets.POSTMAN_API_KEY }}
        collection: 803c9bf5-2198-41b4-a300-4dff364a641d
        environment: 40e995b5-5f6b-4f0a-af3a-c1dfa184c497?apikey=PMAK-642b0897fe492c24f4708e5d-94f6e1dd50fd2a4c545b59eb663eaded73
