name: Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: postmanlabs/postman-action@v1
      with:
           api_key: ${{ secrets.POSTMAN_API_KEY }}
           collection: https://github.com/BayAzat/rcpt/blob/main/.github/workflows/22818271-fae759ee-2adc-41a8-8730-03552a29d60f.json
